//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abyari.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymankarReshte
    {
        public int IDPaymankar { get; set; }
        public int IDReshte { get; set; }
        public Nullable<System.DateTime> TarikhSodorMojavez { get; set; }
        public Nullable<System.DateTime> TarikhEtebarMojavez { get; set; }
        public string ShomareMojavez { get; set; }
        public Nullable<bool> Faal { get; set; }
        public int IDRotbe { get; set; }
    
        public virtual RotbeReshte RotbeReshte { get; set; }
        public virtual Paymankar Paymankar { get; set; }
    }
}
