//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abyari.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewZirProjeMoshtary
    {
        public string Name { get; set; }
        public int ID { get; set; }
        public Nullable<double> Sath { get; set; }
        public Nullable<int> TedadDastgahAbyari { get; set; }
        public string NoePomp { get; set; }
        public Nullable<long> Debi { get; set; }
        public string ManbaeTaminAb { get; set; }
        public Nullable<int> IDPaymankar { get; set; }
        public Nullable<int> IDSherkatTarah { get; set; }
        public Nullable<int> IDRoosta { get; set; }
        public Nullable<int> IDNoe { get; set; }
        public string CodeMeliMoshtary { get; set; }
        public Nullable<double> SahmeDolat { get; set; }
        public Nullable<double> SahmeBank { get; set; }
        public Nullable<double> SahmeMotaghazi { get; set; }
        public string Code { get; set; }
        public string NameMoshtary { get; set; }
        public string Famil { get; set; }
        public string Mobile { get; set; }
        public Nullable<bool> Tahvil { get; set; }
        public string NoeProje { get; set; }
        public string Shahrestan { get; set; }
        public string NamePaymankar { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public Nullable<System.DateTime> PersianContractedDate { get; set; }
    }
}
