//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abyari.Controls {
    
    
    public partial class UscGridWtihAttachment {
        
        /// <summary>
        /// ImportFromExcel_ProjectOne control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebUtility.Controls.ImportFromExcel ImportFromExcel_ProjectOne;
        
        /// <summary>
        /// ImportFromExcel_lolehProjectOne control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebUtility.Controls.ImportFromExcel ImportFromExcel_lolehProjectOne;
        
        /// <summary>
        /// uscFileUplaod control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebUtility.Controls.FileUpload uscFileUplaod;
        
        /// <summary>
        /// grdProjecsSelect control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadGrid grdProjecsSelect;
        
        /// <summary>
        /// selectedProjectID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField selectedProjectID;
    }
}
