//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abyari.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoeLoole
    {
        public NoeLoole()
        {
            this.ZirProjeLooles = new HashSet<ZirProjeLoole>();
        }
    
        public int ID { get; set; }
        public string Noe { get; set; }
        public Nullable<int> Ghotr { get; set; }
        public string Made { get; set; }
        public Nullable<int> Feshar { get; set; }
    
        public virtual ICollection<ZirProjeLoole> ZirProjeLooles { get; set; }
    }
}
