//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abyari.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RotbeReshte
    {
        public RotbeReshte()
        {
            this.PaymankarReshtes = new HashSet<PaymankarReshte>();
        }
    
        public int ID { get; set; }
        public int IDReshte { get; set; }
        public Nullable<int> Rotbe { get; set; }
        public Nullable<int> TedadKarMojaz { get; set; }
        public Nullable<int> SatheMojaz { get; set; }
        public Nullable<bool> Faal { get; set; }
        public Nullable<int> SatheMojazeSalane { get; set; }
    
        public virtual ICollection<PaymankarReshte> PaymankarReshtes { get; set; }
        public virtual Reshte Reshte { get; set; }
    }
}
