//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abyari.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shahrestan
    {
        public int ID { get; set; }
        public Nullable<int> CodeOstan { get; set; }
        public string Sharh { get; set; }
        public string TelePhone { get; set; }
        public string Addres { get; set; }
        public string Fax { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
    }
}
