//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abyari.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewPaymankarReshte
    {
        public int IDPaymankar { get; set; }
        public int IDReshte { get; set; }
        public Nullable<System.DateTime> TarikhSodorMojavez { get; set; }
        public Nullable<System.DateTime> TarikhEtebarMojavez { get; set; }
        public string ShomareMojavez { get; set; }
        public Nullable<bool> Faal { get; set; }
        public string NameReshte { get; set; }
        public string NamePaymankar { get; set; }
        public int IDRotbe { get; set; }
        public Nullable<int> SatheMojaz { get; set; }
        public Nullable<bool> ReshteFaal { get; set; }
        public Nullable<int> Rotbe { get; set; }
        public Nullable<int> TedadKarMojaz { get; set; }
        public Nullable<int> SatheMojazeSalane { get; set; }
        public string CodeEghtesadi { get; set; }
        public string ShenaseMeli { get; set; }
        public Nullable<System.Guid> InvoiceID { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
