//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abyari.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewZirprojeResevation
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<double> Sath { get; set; }
        public Nullable<int> ContractedPaymankarID { get; set; }
        public string Sharh { get; set; }
        public Nullable<bool> Tavafogh { get; set; }
        public string NamePaymankar { get; set; }
        public string Shahrestan { get; set; }
        public Nullable<int> Rotbe { get; set; }
        public int ReservedPaymankarID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> IDShahrestan { get; set; }
        public Nullable<System.DateTime> PersianCreateDate { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
    }
}
