//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abyari.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewMahal
    {
        public string Shahrestan { get; set; }
        public string Bakhsh { get; set; }
        public string Dehestan { get; set; }
        public string Roosta { get; set; }
        public int IDRoosta { get; set; }
        public Nullable<int> IDShahrestan { get; set; }
    }
}
