//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abyari.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewZirProje
    {
        public long RowNumber { get; set; }
        public Nullable<int> ID { get; set; }
        public string Name { get; set; }
        public Nullable<double> Sath { get; set; }
        public Nullable<int> TedadDastgahAbyari { get; set; }
        public string NoePomp { get; set; }
        public Nullable<long> Debi { get; set; }
        public string ManbaeTaminAb { get; set; }
        public Nullable<int> IDPaymankar { get; set; }
        public Nullable<int> IDSherkatTarah { get; set; }
        public Nullable<int> IDRoosta { get; set; }
        public Nullable<int> IDNoe { get; set; }
        public string NoeProje { get; set; }
        public Nullable<int> MeghdareEstesnaSath { get; set; }
        public Nullable<double> ZaribSath { get; set; }
        public string Sharh { get; set; }
        public Nullable<int> IDReshte { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public string Code { get; set; }
        public string CodeMeliMoshtary { get; set; }
        public Nullable<bool> Tahvil { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> WfExecutingID { get; set; }
    }
}
