//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abyari.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZirProjeBaravord
    {
        public int IDZirProje { get; set; }
        public string IDNameFehrestBaha { get; set; }
        public string CodeFaslFehrestBaha { get; set; }
        public string CodeMetrehFehrestBaha { get; set; }
        public string Year { get; set; }
        public Nullable<double> Meghdar { get; set; }
    
        public virtual ZirProje ZirProje { get; set; }
    }
}
