//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abyari.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZirProjeLoole
    {
        public int IDNoeLoole { get; set; }
        public int IDZirProje { get; set; }
        public Nullable<int> Tedad { get; set; }
        public string Vahed { get; set; }
    
        public virtual NoeLoole NoeLoole { get; set; }
        public virtual ZirProje ZirProje { get; set; }
    }
}
