//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abyari.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZirProje
    {
        public ZirProje()
        {
            this.ZirProjeReservations = new HashSet<ZirProjeReservation>();
            this.ZirProjeBaravords = new HashSet<ZirProjeBaravord>();
            this.ZirProjeLooles = new HashSet<ZirProjeLoole>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<double> Sath { get; set; }
        public Nullable<int> TedadDastgahAbyari { get; set; }
        public string NoePomp { get; set; }
        public Nullable<long> Debi { get; set; }
        public string ManbaeTaminAb { get; set; }
        public Nullable<int> IDPaymankar { get; set; }
        public Nullable<int> IDSherkatTarah { get; set; }
        public Nullable<int> IDRoosta { get; set; }
        public Nullable<int> IDNoe { get; set; }
        public string CodeMeliMoshtary { get; set; }
        public Nullable<double> SahmeDolat { get; set; }
        public Nullable<double> SahmeBank { get; set; }
        public Nullable<double> SahmeMotaghazi { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> WfExecutingID { get; set; }
        public Nullable<System.Guid> AttachID { get; set; }
    
        public virtual Moshtary Moshtary { get; set; }
        public virtual NoeProje NoeProje { get; set; }
        public virtual Sherkat Sherkat { get; set; }
        public virtual ZirProjeTahvilMovaghat ZirProjeTahvilMovaghat { get; set; }
        public virtual Paymankar Paymankar { get; set; }
        public virtual ICollection<ZirProjeReservation> ZirProjeReservations { get; set; }
        public virtual ICollection<ZirProjeBaravord> ZirProjeBaravords { get; set; }
        public virtual ICollection<ZirProjeLoole> ZirProjeLooles { get; set; }
    }
}
